name: golimo_driver
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  ### Network Packages ###

  dartz: ^0.10.1
  dio: ^5.0.2
  flutter_dotenv: ^5.0.2
  get_it: ^7.2.0
  ########################
  flutter_svg: ^2.0.2
  flutter_screenutil: ^5.6.1
  flutter_launcher_icons: ^0.12.0
  flutter_bloc: ^8.1.1
  shimmer: ^2.0.0
  animate_do: ^3.0.2
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.0.17
  flutter_google_places: ^0.3.0
  pretty_dio_logger: ^1.3.1
  device_info_plus: ^9.0.3
  intl: ^0.18.0
  flutter_staggered_animations: ^1.1.1
  ua_client_hints: ^1.1.3
  maps_toolkit: ^2.0.1
  google_maps_flutter: ^2.2.4
  country_picker: ^2.0.20
  dash_flags: ^0.1.1
  flutter_localization: ^0.1.14
  image_picker: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/png_images/
    - assets/svg_icons/
    - assets/fonts/
    - assets/map_style/
    - .env

  fonts:
    - family: Alexandria
      fonts:
        - asset: assets/fonts/Alexandria-Bold.ttf
          weight: 700
        - asset: assets/fonts/Alexandria-Medium.ttf
          weight: 500
        - asset: assets/fonts/Alexandria-Light.ttf
          weight: 300
        - asset: assets/fonts/Alexandria-Regular.ttf
          weight: 400
        - asset: assets/fonts/Alexandria-Thin.ttf
          weight: 100
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/png_images/app_icon.ios.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
